apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: html-server-image:latest
    imagePullPolicy: IfNotPresent
    ports: 
    - containerPort: 3000
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"

